js:

  dmWidgetGalleryPlugin:
    
    view:      view
    form:      form
    cycle:     cycle/jquery.cycle.lite-1.0.min
    scroll:    scroll/jquery.simplyscroll-1.0.4

css:

  dmWidgetGalleryPlugin:
    
    view:      view
    form:      form